steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  dir: run/10-2
  args: ['build', '-t', 'gcr.io/checkpoint-ip/cp102', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  dir: run/10-2
  args: ['push', 'gcr.io/checkpoint-ip/cp102']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  dir: run/10-2
  entrypoint: gcloud
  args: ['run', 'deploy', 'cp102', '--image', 'gcr.io/checkpoint-ip/cp102', '--region', 'us-central1', '--port', '80', '--allow-unauthenticated']
images:
- gcr.io/checkpoint-ip/cp102